# Admin routes

stems_admin_blog_overview:
    pattern:  /admin/blog
    defaults: { _controller: StemsBlogBundle:Admin:index }

stems_admin_blog_create:
    pattern:  /admin/blog/create
    defaults: { _controller: StemsBlogBundle:Admin:create }

stems_admin_blog_edit:
    pattern:  /admin/blog/{id}/edit
    defaults: { _controller: StemsBlogBundle:Admin:edit }

stems_admin_blog_delete:
    pattern:  /admin/blog/{id}/delete
    defaults: { _controller: StemsBlogBundle:Admin:delete }

stems_admin_blog_publish:
    pattern:  /admin/blog/{id}/publish
    defaults: { _controller: StemsBlogBundle:Admin:publish }

stems_admin_blog_comments:
    pattern:  /admin/blog/comments
    defaults: { _controller: StemsBlogBundle:Admin:comments }

stems_admin_blog_moderate_comment:
    pattern:  /admin/blog/comment/{id}/moderate
    defaults: { _controller: StemsBlogBundle:Admin:moderateComment }

stems_admin_blog_delete_comment:
    pattern:  /admin/blog/comment/{id}/delete
    defaults: { _controller: StemsBlogBundle:Admin:deleteComment }

# Front-end routes

stems_blog_front_list:
    pattern:  /magazine
    defaults: { _controller: StemsBlogBundle:Front:list }

stems_blog_front_rss:
    pattern:  /blog/rss
    defaults: { _controller: StemsBlogBundle:Front:rss }

stems_blog_front_rss_xml:
    pattern:  /blog/rss.xml
    defaults: { _controller: StemsBlogBundle:Front:rss }

stems_blog_front_preview:
    pattern:  /blog/preview/{slug}
    defaults: { _controller: StemsBlogBundle:Front:preview }

stems_blog_front_post:
    pattern:  /magazine/{slug}
    defaults: { _controller: StemsBlogBundle:Front:post }

# REST routes

stems_rest_blog_get_more_posts:
    pattern:  /rest/blog/get-more-posts/{category}/{offset}
    defaults: { _controller: StemsBlogBundle:Rest:getMorePosts }

stems_rest_blog_add_section_type:
    pattern:  /admin/blog/rest/add-section-type/{type}
    defaults: { _controller: StemsBlogBundle:Rest:addSectionType }

stems_rest_blog_remove_section:
    pattern:  /admin/blog/rest/remove-section/{id}
    defaults: { _controller: StemsBlogBundle:Rest:removeSection }

stems_rest_blog_set_featureimage:
    pattern:  /admin/blog/rest/set-feature-image/{id}
    defaults: { _controller: StemsBlogBundle:Rest:setFeatureImage }

stems_rest_blog_add_comment:
    pattern:  /rest/blog/add-comment/{post}
    defaults: { _controller: StemsBlogBundle:Rest:addComment }

# Popup routes

stems_rest_blog_popup_set_featureimage:
    pattern:  /admin/blog/popup/set-feature-image/{id}
    defaults: { _controller: StemsBlogBundle:Popup:setFeatureImage }

stems_popup_blog_set_imagesectionimage:
    pattern:  /admin/blog/popup/set-imagesection-image/{id}
    defaults: { _controller: StemsBlogBundle:Popup:setImageSectionImage }

stems_rest_blog_popup_add_productgalleryproduct:
    pattern:  /admin/blog/popup/add-product-gallery-product/{id}
    defaults: { _controller: StemsBlogBundle:Popup:addProductGalleryProduct }

stems_rest_blog_popup_update_productgalleryproduct:
    pattern:  /admin/blog/popup/update-product-gallery-product/{id}
    defaults: { _controller: StemsBlogBundle:Popup:updateProductGalleryProduct }